name: controle_estacionamento
description: App para controlar carros estacionados.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  local_auth: ^2.1.7
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - lib/assets/imgs/background.jpg
    - lib/assets/imgs/logo1.png
    - lib/assets/imgs/android_icon.png

flutter_native_splash:
  background_image: "lib/assets/imgs/background.jpg"
  android: true
  ios: true
  android_12:
      # The image parameter sets the splash screen icon image.  If this parameter is not specified,
      # the app's launcher icon will be used instead.
      # Please note that the splash screen will be clipped to a circle on the center of the screen.
      # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
      # 640 pixels in diameter.
      # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
      # 768 pixels in diameter.
      image: lib/assets/imgs/ios_icons.png

      # Splash screen background color.
      color: "#0F297D"

      # App icon background color.
      #icon_background_color: "#111111"

      # The branding property allows you to specify an image used as branding in the splash screen.
      #branding: assets/dart.png

      # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
      # apply when the device is in dark mode. If they are not specified, the app will use the
      # parameters from above.
      #image_dark: assets/android12splash-invert.png
      #color_dark: "#042a49"
      #icon_background_color_dark: "#eeeeee"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/imgs/ios_icons.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#0F297D"
  adaptive_icon_foreground: "lib/assets/imgs/ios_icons.png"

